### ISSUE TITLE
Extract a zip archive to buffer generates an invalid zip archive

### ISSUE THREAD

**Issue by nanw1103** [cthackers/adm-zip#282]
When open and extract a zip archive, it fails. Please use the following code and the attachment to reproduce it.

```javascript
const AdmZip = require('adm-zip')

let zip1 = new AdmZip('./bug-data.zip')	//this zip file can be validated by other zip tools (7z, WinRAR), which should be valid.
//zip1.extractAllTo('./extracted1')		//this does succeed

//actually the following toBuffer() is buggy. It generates an entry with invalid CRC.
//If you write the buffer to a file and examine with zip tools (e.g. WinRAR), it says one entry is corrupted.
let zip2 = new AdmZip(zip1.toBuffer())	

//The following operation will fail: invalid block type
zip2.extractAllTo('./extracted2')
```

[bug-data.zip](https://github.com/cthackers/adm-zip/files/3116015/bug-data.zip)

**Comment by 5saviahv** [comment]
There is error in function `entryHeaderToBinary`
in line: `data.writeInt32LE(_crc & 0xFFFF, Constants.CENCRC, true);`
it should be: `data.writeUInt32LE(_crc & 0xFFFFFFFF, Constants.CENCRC, true);`

it basically masks  32-bit crc to 16-bit, but writes it as 32-bit so half of the data will be lost;
there are also other issue it that line - CRC number write should be using unsigned integer.

**Comment by 5saviahv** [comment]
version 0.4.13 in npm,
there are error in function entryHeaderToBinary - generated file headers are corrupted.

issue is fixed, but npm is not updated

**Comment by iippis** [comment]
@5saviahv could you check that you have pushed the new version to NPM? the issue still persists

**Comment by 5saviahv** [comment]
You should contact @cthackers, he can make changes on npm. Until npm is not updated you may try taking source directly from github by:
> npm i git+https://github.com/cthackers/adm-zip.git

**Comment by curran** [comment]
Possible duplicate of https://github.com/cthackers/adm-zip/issues/289

**Comment by 5saviahv** [comment]
It should be fixed for now
