### ISSUE TITLE
writeZipPromise creates a broken archive when file names have non-ASCII characters

### ISSUE THREAD

**Issue by maykivets** [cthackers/adm-zip#477]
The function "writeZipPromise" creates a broken archive when file names have non-ASCII characters.

Although the function "writeZip" works as expected.

Steps to reproduce:

1. Create a folder or zip archive.
2. Add a file with non-ASCII characters in its name, e.g. "my file копія.png".
3. Try to write a zip using the function "writeZipPromise".

**Comment by Bnaya** [comment]
I also had issues with non-ASCII characters, upgrading to latest version seems to solve it

**Comment by 5saviahv** [comment]
Yes, it should be fixed in repo now.

**Comment by stfbd12138** [comment]
this issue was not fixed. I reproduced, but it's not 100% reproduceable
